/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customers;

import Business.AirPlane;
import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Customer;
import Business.CustomerDirectory;
import Business.Flight;
import Business.FlightDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;

/**
 *
 * @author saurabhgujare
 */
public class CustomerSearchPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerSearchPanel
     */
    AirlinerDirectory airlinerList;
    JPanel rightPanel;
    CustomerDirectory customerDirectory;
    Customer customer;
    //FlightDirectory flightList;
    
    public CustomerSearchPanel(AirlinerDirectory airlinerList, JPanel rightPanel, CustomerDirectory customerDirectory, Customer customer) {
        initComponents();
        this.airlinerList=airlinerList;
        this.rightPanel=rightPanel;
        this.customerDirectory=customerDirectory;
        this.customer=customer;
        //this.flightList=flightList;
        
        searchCustomerCB.removeAllItems();
        for(Customer customer1 : customerDirectory.getCustomerList()) {
           searchCustomerCB.addItem(customer1);
        }  
        refreshTable();
    }
    
    public void refreshTable() {
        
        int rowCount = bookingTbl.getRowCount();
        DefaultTableModel model = (DefaultTableModel)bookingTbl.getModel();
        model.setRowCount(0);
//        for(int i=rowCount-1;i>=0;i--) {
//            model.removeRow(i);
//        }
        
        for(Airliner a : airlinerList.getAirlinerList()) {
            for(AirPlane ap : a.getAirplaneDirectory().getAirplaneList()){
                for(Flight f : ap.getFlightdirectory().getFlightList()){
                    Object row[] = new Object[model.getColumnCount()];
                    row[0] = a;
                    row[1] = f;
                    row[2] = f.getDepartDate().getMonth()+"/"+f.getDepartDate().getDate()+"/"+((f.getDepartDate().getYear())+1900);
                    row[3] = f.getDepartLoc();
                    row[4] = f.getArrivalLoc();
                    row[5] = String.valueOf(f.getDepartureHr()+":"+f.getDepartureMin());
                    row[6] = f.getPriceFlight();
                    model.addRow(row);
                }
            }
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchCustomerCB = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        fromTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        toTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookingTbl = new javax.swing.JTable();
        bookSeatBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(249, 225, 217));
        setPreferredSize(new java.awt.Dimension(699, 527));

        searchCustomerCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        searchCustomerCB.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                onSelectCB(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Search Flight");

        jLabel2.setText("TO*");

        jLabel3.setText("FROM*");

        jLabel4.setText("Search Customer ");

        jLabel5.setText("Date*");

        bookingTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Airliner", "Flight", "Date", "From", "To", "Departing Time", "Price"
            }
        ));
        jScrollPane1.setViewportView(bookingTbl);

        bookSeatBtn.setText("Book a Seat");
        bookSeatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookSeatBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jButton2.setText("View Booking");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(bookSeatBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(toTF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fromTF, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(188, 188, 188)
                                        .addComponent(searchBtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(165, 165, 165)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(searchCustomerCB, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(78, 78, 78))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {fromTF, toTF});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchCustomerCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookSeatBtn)
                .addGap(25, 25, 25))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {fromTF, toTF});

    }// </editor-fold>//GEN-END:initComponents

    private void onSelectCB(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_onSelectCB
        // TODO add your handling code here:
    }//GEN-LAST:event_onSelectCB

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
//        if(toTF.getText().isEmpty()||fromTF.getText().isEmpty()){
//            JOptionPane.showMessageDialog(null, "Please fill all the mandatory fields");
//        }else{
            int rowCount = bookingTbl.getRowCount();
            DefaultTableModel model = (DefaultTableModel)bookingTbl.getModel();
            model.setRowCount(0);

            for(Airliner a : airlinerList.getAirlinerList()) {
                for(AirPlane ap : a.getAirplaneDirectory().getAirplaneList()){
                    for(Flight f : ap.getFlightdirectory().getFlightList()){
                        if(f.getDepartLoc().equalsIgnoreCase(toTF.getText())&&f.getArrivalLoc().equalsIgnoreCase(fromTF.getText())){
                        Object row[] = new Object[model.getColumnCount()];
                        row[0] = a;
                        row[1] = f;
                        row[2] = f.getDepartDate();
                        row[3] = f.getDepartLoc();
                        row[4] = f.getArrivalLoc();
                        row[5] = String.valueOf(f.getDepartureHr()+":"+f.getDepartureMin());
                        row[6] = f.getPriceFlight();
                        model.addRow(row);
                        }
                    }
                }
            }
        //}
    }//GEN-LAST:event_searchBtnActionPerformed

    private void bookSeatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookSeatBtnActionPerformed
        // TODO add your handling code here:
        Customer customer1 = (Customer)searchCustomerCB.getSelectedItem();

        Flight flight1 =(Flight) bookingTbl.getValueAt(bookingTbl.getSelectedRow(), 1);
        
        seatBookingPanel seatBooking = new seatBookingPanel(flight1.getSeatArray(),rightPanel, customer1);
        
        rightPanel.add("seatBookingPanel",seatBooking);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);                            
    }//GEN-LAST:event_bookSeatBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Customer customer1 = (Customer)searchCustomerCB.getSelectedItem();
        bookingHistoryPanel historyPanel = new bookingHistoryPanel(rightPanel, customer1);
        
        rightPanel.add("seatBookingPanel",historyPanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);   
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookSeatBtn;
    private javax.swing.JTable bookingTbl;
    private javax.swing.JTextField fromTF;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox searchCustomerCB;
    private javax.swing.JTextField toTF;
    // End of variables declaration//GEN-END:variables
}
