/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
/**
 *
 * @author saurabhgujare
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    public ViewPanel(Person person) {
        initComponents();
        display(person);
    }
    
    private void display(Person person){
        String first_name= person.getFirst_name();
        firstNameTF.setText(first_name);
        firstNameTF.setEnabled(false);
        
        String last_name=person.getLast_name();
        lastNameTF.setText(last_name);
        lastNameTF.setEnabled(false);
        
        String dob=person.getDob();
        dobTF.setText(dob);
        dobTF.setEnabled(false);
        
        String work_add_line1=person.getWork_address().getAddress_line1();
        workAdrLine1TF.setText(work_add_line1);
        workAdrLine1TF.setEnabled(false);
        String work_add_line2=person.getWork_address().getAddress_line2();
        workAdrLine2TF.setText(work_add_line2);
        workAdrLine2TF.setEnabled(false);
        String work_city=person.getWork_address().getCity();
        workCityTF.setText(work_city);
        workCityTF.setEnabled(false);
        String work_state=person.getWork_address().getState();
        workStateTF.setText(work_state);
        workStateTF.setEnabled(false);
        String work_zipcode=person.getWork_address().getZipcode();
        workZipcodeTF.setText(work_zipcode);
        workZipcodeTF.setEnabled(false);
        String work_country=person.getWork_address().getCountry();
        workCountryTF.setText(work_country);
        workCountryTF.setEnabled(false);
        
        String local_add_line1=person.getLocal_address().getAddress_line1();
        localAdrLine1TF.setText(local_add_line1);
        localAdrLine1TF.setEnabled(false);
        String local_add_line2=person.getLocal_address().getAddress_line2();
        localAdrLine2TF.setText(local_add_line2);
        localAdrLine2TF.setEnabled(false);
        String local_city=person.getLocal_address().getCity();
        localCityTF.setText(local_city);
        localCityTF.setEnabled(false);
        String local_state=person.getLocal_address().getState();
        localStateTF.setText(local_state);
        localStateTF.setEnabled(false);
        String local_zipcode=person.getLocal_address().getZipcode();
        localZipcodeTF.setText(local_zipcode);
        localZipcodeTF.setEnabled(false);
        String local_country=person.getLocal_address().getCountry();
        localCountryTF.setText(local_country);
        localCountryTF.setEnabled(false);
        
        String home_add_line1=person.getHome_address().getAddress_line1();
        homeAdrLine1TF.setText(home_add_line1);
        homeAdrLine1TF.setEnabled(false);
        String home_add_line2=person.getHome_address().getAddress_line2();
        homeAdrLine2TF.setText(home_add_line2);
        homeAdrLine2TF.setEnabled(false);
        String home_city=person.getHome_address().getCity();
        homeCityTF.setText(home_city);
        homeCityTF.setEnabled(false);
        String home_state=person.getHome_address().getState();
        homeStateTF.setText(home_state);
        homeStateTF.setEnabled(false);
        String home_zipcode=person.getHome_address().getZipcode();
        homeZipcodeTF.setText(home_zipcode);
        homeZipcodeTF.setEnabled(false);
        String home_country=person.getHome_address().getCountry();
        homeCountryTF.setText(home_country);
        homeCountryTF.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        workAddressPanel = new javax.swing.JPanel();
        workAdrLine1TF = new javax.swing.JTextField();
        workAdrLine2TF = new javax.swing.JTextField();
        workCityTF = new javax.swing.JTextField();
        workStateTF = new javax.swing.JTextField();
        workZipcodeTF = new javax.swing.JTextField();
        workCountryTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        State = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        localAddressPanel = new javax.swing.JPanel();
        localAdrLine1TF = new javax.swing.JTextField();
        localAdrLine2TF = new javax.swing.JTextField();
        localCityTF = new javax.swing.JTextField();
        localStateTF = new javax.swing.JTextField();
        localZipcodeTF = new javax.swing.JTextField();
        localCountryTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        sweetHomeAddressPanel = new javax.swing.JPanel();
        homeAdrLine1TF = new javax.swing.JTextField();
        homeAdrLine2TF = new javax.swing.JTextField();
        homeCityTF = new javax.swing.JTextField();
        homeStateTF = new javax.swing.JTextField();
        homeZipcodeTF = new javax.swing.JTextField();
        homeCountryTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        firstNameTF = new javax.swing.JTextField();
        lastNameTF = new javax.swing.JTextField();
        dobLabel = new javax.swing.JLabel();
        dobTF = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(965, 567));
        setSize(new java.awt.Dimension(965, 567));
        setLayout(new java.awt.BorderLayout());

        workAddressPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Work Address"));

        workAdrLine1TF.setText("jTextField1");
        workAdrLine1TF.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        workAdrLine2TF.setText("jTextField2");
        workAdrLine2TF.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        workCityTF.setText("jTextField3");
        workCityTF.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        workStateTF.setText("jTextField4");
        workStateTF.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        workZipcodeTF.setText("jTextField5");
        workZipcodeTF.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        workCountryTF.setText("jTextField6");
        workCountryTF.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel1.setText("Street Line 1");

        jLabel2.setText("Street Line 2");

        jLabel3.setText("City");

        State.setText("State");

        jLabel5.setText("ZipCode");

        jLabel6.setText("Country");

        javax.swing.GroupLayout workAddressPanelLayout = new javax.swing.GroupLayout(workAddressPanel);
        workAddressPanel.setLayout(workAddressPanelLayout);
        workAddressPanelLayout.setHorizontalGroup(
            workAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAddressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workAddressPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(workAdrLine1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workAddressPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(workCountryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workAddressPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(workAdrLine2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workAddressPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(workCityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workAddressPanelLayout.createSequentialGroup()
                        .addComponent(State)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(workStateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workAddressPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(workZipcodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        workAddressPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {workAdrLine1TF, workAdrLine2TF, workCityTF, workCountryTF, workStateTF, workZipcodeTF});

        workAddressPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {State, jLabel1, jLabel2, jLabel3, jLabel5, jLabel6});

        workAddressPanelLayout.setVerticalGroup(
            workAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAddressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workAdrLine1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(workAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workAdrLine2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(workAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workCityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(workAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workStateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(State))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(workAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workZipcodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(workAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workCountryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33))
        );

        workAddressPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {workAdrLine1TF, workAdrLine2TF, workCityTF, workCountryTF, workStateTF, workZipcodeTF});

        workAddressPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {State, jLabel1, jLabel2, jLabel3, jLabel5, jLabel6});

        localAddressPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Local Address"));

        localAdrLine1TF.setText("jTextField1");
        localAdrLine1TF.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        localAdrLine1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localAdrLine1TFActionPerformed(evt);
            }
        });

        localAdrLine2TF.setText("jTextField2");
        localAdrLine2TF.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        localCityTF.setText("jTextField3");
        localCityTF.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        localStateTF.setText("jTextField4");
        localStateTF.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        localZipcodeTF.setText("jTextField5");
        localZipcodeTF.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        localCountryTF.setText("jTextField6");
        localCountryTF.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel7.setText("Street Line 1");

        jLabel8.setText("Street Line 2");

        jLabel9.setText("City");

        jLabel10.setText("State");

        jLabel11.setText("ZipCode");

        jLabel12.setText("Country");

        javax.swing.GroupLayout localAddressPanelLayout = new javax.swing.GroupLayout(localAddressPanel);
        localAddressPanel.setLayout(localAddressPanelLayout);
        localAddressPanelLayout.setHorizontalGroup(
            localAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(localAddressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(localAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(localAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(localAdrLine2TF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localCityTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localStateTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localZipcodeTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localCountryTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localAdrLine1TF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        localAddressPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel7, jLabel8, jLabel9});

        localAddressPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {localAdrLine1TF, localAdrLine2TF, localCityTF, localCountryTF, localStateTF, localZipcodeTF});

        localAddressPanelLayout.setVerticalGroup(
            localAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(localAddressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(localAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localAdrLine1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(localAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localAdrLine2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(localAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localCityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(localAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localStateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(localAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localZipcodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(localAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localCountryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(33, 33, 33))
        );

        localAddressPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel7, jLabel8, jLabel9});

        localAddressPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {localAdrLine1TF, localAdrLine2TF, localCityTF, localCountryTF, localStateTF, localZipcodeTF});

        sweetHomeAddressPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Sweet Home Address"));

        homeAdrLine1TF.setText("jTextField1");
        homeAdrLine1TF.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        homeAdrLine2TF.setText("jTextField2");
        homeAdrLine2TF.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        homeCityTF.setText("jTextField3");
        homeCityTF.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        homeStateTF.setText("jTextField4");
        homeStateTF.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        homeZipcodeTF.setText("jTextField5");
        homeZipcodeTF.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        homeCountryTF.setText("jTextField6");
        homeCountryTF.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel13.setText("Street Line 1");

        jLabel14.setText("Street Line 2");

        jLabel15.setText("City");

        jLabel16.setText("State");

        jLabel17.setText("ZipCode");

        jLabel18.setText("Country");

        javax.swing.GroupLayout sweetHomeAddressPanelLayout = new javax.swing.GroupLayout(sweetHomeAddressPanel);
        sweetHomeAddressPanel.setLayout(sweetHomeAddressPanelLayout);
        sweetHomeAddressPanelLayout.setHorizontalGroup(
            sweetHomeAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sweetHomeAddressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sweetHomeAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(sweetHomeAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeAdrLine2TF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeCityTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeStateTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeZipcodeTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeCountryTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeAdrLine1TF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        sweetHomeAddressPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {homeAdrLine1TF, homeAdrLine2TF, homeCityTF, homeCountryTF, homeStateTF, homeZipcodeTF});

        sweetHomeAddressPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel13, jLabel14, jLabel15, jLabel16, jLabel17, jLabel18});

        sweetHomeAddressPanelLayout.setVerticalGroup(
            sweetHomeAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sweetHomeAddressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sweetHomeAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeAdrLine1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(sweetHomeAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeAdrLine2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(sweetHomeAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeCityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(sweetHomeAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeStateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(sweetHomeAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeZipcodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(sweetHomeAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeCountryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(33, 33, 33))
        );

        sweetHomeAddressPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {homeAdrLine1TF, homeAdrLine2TF, homeCityTF, homeCountryTF, homeStateTF, homeZipcodeTF});

        sweetHomeAddressPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel13, jLabel14, jLabel15, jLabel16, jLabel17, jLabel18});

        firstNameLabel.setText("First Name");

        lastNameLabel.setText("Last Name");

        firstNameTF.setText("firstNameTF");
        firstNameTF.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        firstNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTFActionPerformed(evt);
            }
        });

        lastNameTF.setText("lastNameTF");
        lastNameTF.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        lastNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTFActionPerformed(evt);
            }
        });

        dobLabel.setText("DOB (YYYY/MM/DD)");

        dobTF.setText("dobTF");
        dobTF.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(workAddressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(localAddressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sweetHomeAddressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel)
                            .addComponent(lastNameLabel)
                            .addComponent(dobLabel))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dobTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dobTF, firstNameTF, lastNameTF});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dobLabel, firstNameLabel, lastNameLabel});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {localAddressPanel, sweetHomeAddressPanel, workAddressPanel});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLabel)
                    .addComponent(dobTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(workAddressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(localAddressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sweetHomeAddressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dobTF, firstNameTF, lastNameTF});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dobLabel, firstNameLabel, lastNameLabel});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {localAddressPanel, sweetHomeAddressPanel, workAddressPanel});

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTFActionPerformed

    private void lastNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTFActionPerformed

    private void localAdrLine1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localAdrLine1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localAdrLine1TFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel State;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField dobTF;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTF;
    private javax.swing.JTextField homeAdrLine1TF;
    private javax.swing.JTextField homeAdrLine2TF;
    private javax.swing.JTextField homeCityTF;
    private javax.swing.JTextField homeCountryTF;
    private javax.swing.JTextField homeStateTF;
    private javax.swing.JTextField homeZipcodeTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTF;
    private javax.swing.JPanel localAddressPanel;
    private javax.swing.JTextField localAdrLine1TF;
    private javax.swing.JTextField localAdrLine2TF;
    private javax.swing.JTextField localCityTF;
    private javax.swing.JTextField localCountryTF;
    private javax.swing.JTextField localStateTF;
    private javax.swing.JTextField localZipcodeTF;
    private javax.swing.JPanel sweetHomeAddressPanel;
    private javax.swing.JPanel workAddressPanel;
    private javax.swing.JTextField workAdrLine1TF;
    private javax.swing.JTextField workAdrLine2TF;
    private javax.swing.JTextField workCityTF;
    private javax.swing.JTextField workCountryTF;
    private javax.swing.JTextField workStateTF;
    private javax.swing.JTextField workZipcodeTF;
    // End of variables declaration//GEN-END:variables
}
