/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Airliners;

import Business.AirPlane;
import Business.Airliner;
import Business.AirlinerDirectory;
import Business.AirplaneDirectory;
import Business.Flight;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saurabhgujare
 */
public class FlightLoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form FlightLoginPanel
     */
    //AirplaneDirectory airplaneList;
    JPanel rightPanel;
    AirPlane airplane;
    List<AirPlane> airplaneList;

    public FlightLoginPanel(JPanel rightPanel, Airliner airliner) {
        initComponents();
        this.rightPanel=rightPanel;

        this.airplaneList = airliner.getAirplaneDirectory().getAirplaneList();
        
        airlinerNameTF.setText(airliner.getAirlinerName());
        
        airplaneIdCB.removeAllItems();
        for(AirPlane airplane : airplaneList) {
           airplaneIdCB.addItem(airplane);
        }
        
        refreshTable();
    }


    public void refreshTable() {
        if(airplaneIdCB.getSelectedIndex()==-1){
            return;
        }
        int rowCount = flightTbl.getRowCount();
        DefaultTableModel model = (DefaultTableModel)flightTbl.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        airplane = airplaneList.get(airplaneIdCB.getSelectedIndex());
        for(Flight p : airplane.getFlightdirectory().getFlightList()) {
            Object row[] = new Object[4];
            row[0] = p;
            row[1] = p.getDepartDate().getMonth()+"/"+p.getDepartDate().getDate()+"/"+((p.getDepartDate().getYear())+1900);
            row[2] = p.getArrivalLoc();
            row[3] = p.getDepartLoc();
            model.addRow(row);
            }
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        airlinerNameTF = new javax.swing.JTextField();
        airplaneIdCB = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        addFlightBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        removeFlightBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightTbl = new javax.swing.JTable();

        setBackground(new java.awt.Color(144, 186, 244));
        setPreferredSize(new java.awt.Dimension(699, 527));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Add Flight");

        airlinerNameTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        airlinerNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlinerNameTFActionPerformed(evt);
            }
        });

        airplaneIdCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        airplaneIdCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onSelectCB(evt);
            }
        });
        airplaneIdCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airplaneIdCBActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Select Airplane");

        addFlightBtn.setText("Add Flight");
        addFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        removeFlightBtn.setText("Remove Flight");
        removeFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFlightBtnActionPerformed(evt);
            }
        });

        viewBtn.setText("View Flight");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        flightTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Flight No", "Date", "To", "From"
            }
        ));
        jScrollPane1.setViewportView(flightTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(airplaneIdCB, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addFlightBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeFlightBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(airlinerNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addFlightBtn, removeFlightBtn, viewBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(airlinerNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airplaneIdCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFlightBtn)
                    .addComponent(viewBtn)
                    .addComponent(removeFlightBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void airlinerNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlinerNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airlinerNameTFActionPerformed

    private void addFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightBtnActionPerformed
        // TODO add your handling code here:
       if(airplaneIdCB.getItemCount()<=0){
           JOptionPane.showMessageDialog(null, "Airplane not selected");
       }else{
        AddFlightPanel addFlight = new AddFlightPanel(rightPanel,airplaneList.get(airplaneIdCB.getSelectedIndex()).getFlightdirectory());
        rightPanel.add("AddFlightPanel",addFlight);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
       }
    }//GEN-LAST:event_addFlightBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);
                     
    }//GEN-LAST:event_backBtnActionPerformed

    private void airplaneIdCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airplaneIdCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airplaneIdCBActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = flightTbl.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
        else{
        Flight flight=(Flight) flightTbl.getValueAt(selectedRow, 0);
        ViewFlightPanel viewFlight = new ViewFlightPanel(flight, rightPanel,airplaneList.get(airplaneIdCB.getSelectedIndex()).getFlightdirectory());
        rightPanel.add("ViewFlightPanel",viewFlight);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void removeFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFlightBtnActionPerformed
        // TODO add your handling code here:
        int row = flightTbl.getSelectedRow();
        
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Flight flight = (Flight)flightTbl.getValueAt(row, 0);
        airplane.getFlightdirectory().deleteFlight(flight);
        refreshTable();
    }//GEN-LAST:event_removeFlightBtnActionPerformed

    private void onSelectCB(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_onSelectCB
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_onSelectCB


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFlightBtn;
    private javax.swing.JTextField airlinerNameTF;
    private javax.swing.JComboBox airplaneIdCB;
    private javax.swing.JButton backBtn;
    private javax.swing.JTable flightTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeFlightBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
