/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Airliners;

import Business.AirPlane;
import Business.Airliner;
import Business.AirlinerDirectory;
import Business.AirplaneDirectory;
import Business.Flight;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saurabhgujare
 */
public class FlightLoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form FlightLoginPanel
     */
    AirplaneDirectory airplaneList;
    AirlinerDirectory airlinerList;
    JPanel rightPanel;
    AirPlane airplane;  
    Airliner airliner;
    
    public FlightLoginPanel( AirplaneDirectory airplaneList, JPanel rightPanel, Airliner airliner) {
        initComponents();
        this.rightPanel=rightPanel;
        this.airlinerList=airlinerList;
        this.airliner=airliner;
        
        airlinerNameTF.setText(airliner.getAirlinerName());
        
        airplaneIdCB.removeAllItems();
        for(AirPlane airplane : airplaneList.getAirplaneList()) {
           airplaneIdCB.addItem(airplane);
        }
        
        refreshTable();
    }


    public void refreshTable() {
        int rowCount = flightTbl.getRowCount();
        DefaultTableModel model = (DefaultTableModel)flightTbl.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        airplane = airliner.getAirplaneDirectory().getAirplaneList().get(airplaneIdCB.getSelectedIndex());
        for(Flight p : airplane.getFlightdirectory().getFlightList()) {
            Object row[] = new Object[4];
            row[0] = p;
            row[1] = p.getDepartDate();
            row[2] = p.getArrivalLoc();
            row[3] = p.getDepartLoc();
            model.addRow(row);
            }
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        airlinerNameTF = new javax.swing.JTextField();
        airplaneIdCB = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        addFlightBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        removeFlightBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightTbl = new javax.swing.JTable();

        jLabel1.setText("Flight Login");

        airlinerNameTF.setText("Airliner Name");
        airlinerNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlinerNameTFActionPerformed(evt);
            }
        });

        airplaneIdCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        airplaneIdCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airplaneIdCBActionPerformed(evt);
            }
        });

        jLabel2.setText("Airplane ID");

        addFlightBtn.setText("Add Flight");
        addFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        removeFlightBtn.setText("Remove Flight");

        jButton3.setText("View Flight");

        flightTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Flight No", "Date", "To", "From"
            }
        ));
        jScrollPane1.setViewportView(flightTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(242, 242, 242)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(airlinerNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(airplaneIdCB, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(backBtn)))
                        .addGap(127, 127, 127))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(addFlightBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton3)
                            .addGap(18, 18, 18)
                            .addComponent(removeFlightBtn))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(airlinerNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airplaneIdCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeFlightBtn)
                    .addComponent(jButton3)
                    .addComponent(addFlightBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void airlinerNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlinerNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airlinerNameTFActionPerformed

    private void addFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightBtnActionPerformed
        // TODO add your handling code here:
       
        AddFlightPanel addFlight = new AddFlightPanel(airlinerList, rightPanel,airliner.getAirplaneDirectory().getAirplaneList().get(airplaneIdCB.getSelectedIndex()).getFlightdirectory());
        rightPanel.add("AddFlightPanel",addFlight);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_addFlightBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);
                     
    }//GEN-LAST:event_backBtnActionPerformed

    private void airplaneIdCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airplaneIdCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airplaneIdCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFlightBtn;
    private javax.swing.JTextField airlinerNameTF;
    private javax.swing.JComboBox airplaneIdCB;
    private javax.swing.JButton backBtn;
    private javax.swing.JTable flightTbl;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeFlightBtn;
    // End of variables declaration//GEN-END:variables
}
